### ISSUE TITLE
I need some help

### ISSUE THREAD

**Issue by ghost** [burgil/burgil.github.io#2]
I have a few questions about this project.

If you don't mind sharing your telegram or discord ID

I want to get ahold of you asap.

Many thanks for considering my request.

**Comment by burgil** [comment]
Sorry If you have any questions share them here.

**Comment by ghost** [comment]
We need your services:

Sure thing, I'm looking to build something like this for my personal use and include a few other features as we go along.

I need a bot to automate certain tasks and features for platforms such as tinder, TikTok, Reddit, Facebook, YouTube, and others. I believe you have the experience and ability to create bots and automated tools.

We also need a gaming app built for android and iOS platforms.

feel free to drop me a msg [https://t.me/Digitransactions](url)

Looking forward to working with you soon.

Thank you so much for your attention and participation.

**Comment by burgil** [comment]
No thanks sounds like it will break the TOS of tinder, TikTok, Reddit, Facebook, YouTube, and others.

Good luck.
